#!/bin/env bash
#configuring domain zone/load balancing

# function to retrieve DNS records for a domain and subdomain
function get_dns_records() {
  local domain="$1"
  local subdomain="$2"
  if [ -n "$subdomain" ]; then
    dig +short "$subdomain.$domain" | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, "A", $0}'
  else
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
      dig +short "$subdomain.$domain" | awk -v subdomain="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, "A", $0}'
    done
  fi
}

# check for domain parameter
if [ -z "$1" ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

# check for subdomain parameter
if [ -n "$2" ]; then
  # display DNS records for specified subdomain
  get_dns_records "$1" "$2"
else
  # display DNS records for default subdomains
  get_dns_records "$1"
fi

