#!/usr/bin/env bash
# installs Nginx with the below configuration
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html/index.html;
     server_name nginx-test.test
     return 200 "Hello World";
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart

