#!/usr/bin/env bash
# installs Nginx with the below configuration
apt-get update
apt-get install -y nginx

mkdir /var/www/html/mysite
touch /var/www/html/mysite/index.html
echo "Hello World" > /var/www/html/mysite/index.html
sudo printf %s "server {
     listen      80;
     listen      [::]:80;
     root        /var/www/html/mysite/;
     index       index.html index.htm;
}" > "/etc/nginx/sites-available/newsite.com"

 sudo service nginx restart

