#!/usr/bin/env bash
# installs Nginx with the below configuration
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/testfile/html/index.html
echo "Hello World" > /etc/testfile/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;r
     root        /etc/testfile/html/;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

 sudo nginx -s reload

