#!/usr/bin/env bash
#redirection file
sudo apt-get -y update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
repl_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$repl_str/" /etc/nginx/sites-available/default
sudo service nginx restart

