#!/usr/bin/env bash
#redirection file
sudo apt-get -y update
sudo chown -R "$USER":"$USER" /var/www/html/
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html;
repl_str="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$repl_str/" /etc/ngnix/sites-available/default
 sudo service nginx restart

