#!/usr/bin/env bash
#configuring nginx 404 page

sudo apt-get -y update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
repl_str="root \/var\/www\/html;\n\terror_page 404 \/error.html;"
sudo sed -i "s/root \/var\/www\/html;/$repl_str/" /etc/nginx/sites-available/default
sudo service nginx restart
