#!/usr/bin/env bash
#configuring nginx 404 page

sudo apt-get -y update
sudo apt-get install -y nginx

echo "<Ceci n'est pas une page>" |sudo tee /var/www/html/index.html;
repl_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$repl_str/" /etc/ngnix/sites-available/default
sudo service nginx restart
