#!/usr/bin/env bash
#double the number of webservers(load balancee)

sudo apt-get update
sudo apt-get install nginx

HOSTNAME=$(hostname)
sudo echo "add_header X-Served-By $HOSTNAME;" > /etc/nginx/sites-available/default
sudo service nginx restart
