#!/usr/bin/env bash
#create a file 'signature.key' on your home machine
#copy pub key here 'https://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html' into signature.key
sudo apt-key add signature.key
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update
sudo apt-cache policy mysql-server
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
