#!/usr/bin/env bash
#configure a server so that Nginx runs and listens on port 80

rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
